### ISSUE TITLE
Error: crate directory is missing a `Cargo.toml` file; is `-Z` the wrong directory?

### ISSUE THREAD

**Issue by CyberShadow** [cerrno/pcisph-wasm#3]
Following the directions in the README, trying to run `npm run serve` fails with this output:

```
$ npm run serve

> serve
> cross-env RUSTUP_TOOLCHAIN=nightly RUSTFLAGS='-C target-feature=+atomics,+bulk-memory,+mutable-globals' webpack serve --mode production

Building in production mode
🧐  Checking for wasm-pack...

✅  wasm-pack is installed at /home/vladimir/work/extern/pcisph-wasm/node_modules/.bin/wasm-pack. 

ℹ️  Compiling your crate in release mode...

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/vladimir/work/extern/pcisph-wasm
Error: crate directory is missing a `Cargo.toml` file; is `-Z` the wrong directory?
/home/vladimir/work/extern/pcisph-wasm/node_modules/webpack/lib/util/hash/wasm-hash.js:154
			new WebAssembly.Instance(wasmModule),
			^

RangeError: WebAssembly.Instance(): Out of memory: wasm memory
    at create (/home/vladimir/work/extern/pcisph-wasm/node_modules/webpack/lib/util/hash/wasm-hash.js:154:4)
    at module.exports (/home/vladimir/work/extern/pcisph-wasm/node_modules/webpack/lib/util/createHash.js:160:27)
    at /home/vladimir/work/extern/pcisph-wasm/node_modules/webpack/lib/ChunkGraph.js:1475:17
    at RuntimeSpecMap.provide (/home/vladimir/work/extern/pcisph-wasm/node_modules/webpack/lib/util/runtime.js:495:33)
    at ChunkGraph._getModuleGraphHashBigInt (/home/vladimir/work/extern/pcisph-wasm/node_modules/webpack/lib/ChunkGraph.js:1474:37)
    at /home/vladimir/work/extern/pcisph-wasm/node_modules/webpack/lib/ChunkGraph.js:1501:27
    at RuntimeSpecMap.provide (/home/vladimir/work/extern/pcisph-wasm/node_modules/webpack/lib/util/runtime.js:495:33)
    at ChunkGraph._getModuleGraphHashWithConnections (/home/vladimir/work/extern/pcisph-wasm/node_modules/webpack/lib/ChunkGraph.js:1500:41)
    at ChunkGraph.getModuleGraphHash (/home/vladimir/work/extern/pcisph-wasm/node_modules/webpack/lib/ChunkGraph.js:1445:11)
    at NormalModule.updateHash (/home/vladimir/work/extern/pcisph-wasm/node_modules/webpack/lib/Module.js:713:26)

Node.js v17.3.0
```

**Comment by lucas-schuermann** [comment]
Should be fixed now at HEAD
